version: '3.8'

services:
  postgresBeja:
    image: postgres:latest
    container_name: postgresBeja
    environment:
      POSTGRES_DB: BejapastelesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresalejandro
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
       PGADMIN_DEFAULT_EMAIL: admin@admin.com
       PGADMIN_DEFAULT_PASSWORD: postgresalejandro
    ports:
      - "8090:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
  app:
    build: .
    container_name: appSpring
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - CONNECTION_URL=${CONNECTION_URL}
    ports:
      - "8080:8080"
    depends_on:
      - postgresBeja
    networks:
      - postgres_network
networks:
  postgres_network:

volumes:
  postgres_data:
  pgadmin_data:
